### ISSUE TITLE
Christmas trees

### ISSUE THREAD

**Issue by sinanna** [nobohan/OpenArdenneMap#1]
Hi Julien,

which tagging scheme do you render as christmas tree plantations?(https://github.com/nobohan/OpenArdenneMap/commit/fa539818722584b6de0846c0035289dab59da4b0)

[landuse=plant_nursery + plant=tree + trees=christmas_trees](https://wiki.openstreetmap.org/wiki/Tag:landuse=plant_nursery#Christmas_tree_plantation) or another one?

**Comment by nobohan** [comment]
I use   `produce=christmas_trees` for rendering in my map. 

In OSM, I use the following tagging scheme:

landuse=farmland + produce=christmas_trees. 

But I'm on the point to ask to the OSM tagging list / forum which tagging scheme is the better! Have a look at http://overpass-turbo.eu/s/yYs and http://overpass-turbo.eu/s/yYt: both scheme are used worldwide.

**Comment by nobohan** [comment]
See the question on the forum: https://help.openstreetmap.org/questions/63597/how-to-tag-christmas-trees-plantations

**Comment by sinanna** [comment]
There is no better, but IMHO it was wrong to invent a new scheme, since _trees=christmas_trees_ has been there before.

**Comment by nobohan** [comment]
Sure. But produce=christmas_trees is also present in the OSM wiki: https://wiki.openstreetmap.org/wiki/Key:produce. It could be removed from that page.
