### ISSUE TITLE
Rendering sometimes failed due to invalid polygon geometry errors

### ISSUE THREAD

**Issue by hholzgra** [nobohan/OpenArdenneMap#5]
The waterway_label query sometimes fails with:

`ERROR:  Polygon is invalid : exterior ring doesn't cover interior ring 0`

One of the polygons this happens with is:

https://www.openstreetmap.org/relation/9344592

The actual problem doesn't seem to be the relation itself, as

```
SELECT ST_LineMerge(ST_ApproximateMedialAxis(way)) AS way
                      FROM planet_osm_polygon
                     WHERE osm_id = -9344592;
```
works. It is only the addition of `ST_SimplifyPreserveTopology()`

```
SELECT ST_LineMerge(ST_ApproximateMedialAxis(ST_SimplifyPreserveTopology(way, 50))) AS way
                      FROM planet_osm_polygon
                     WHERE osm_id = -9344592;
```

So what seems to happen in this case is that due to the simplification step the island close to the lakes outer bank is no longer fully inside the lake.

**Comment by hholzgra** [comment]
Adding an extra `ST_ExteriorRing()` seems to help:

```
 @@ -504,7 +504,7 @@
                 WHERE waterway IN ('canal', 'river', 'stream') AND name IS NOT NULL
                 UNION ALL
                 SELECT
-                    ST_LineMerge(ST_ApproximateMedialAxis(ST_SimplifyPreserveTopology(way, 50))) AS way,
+                    ST_LineMerge(ST_ApproximateMedialAxis(ST_SimplifyPreserveTopology(ST_ExteriorRing(way), 50))) AS way,
                     water AS type,
                     replace(replace(name, 'Etang', 'Étg'), 'Étang', 'Étg') AS name
                 FROM planet_osm_polygon

```

**Comment by nobohan** [comment]
Thanks Hartmut! I've added the ST_ExteriorRing function and I'll test it in the next maps I'll produce.
